namespace ApiTest
{
    public static class TestData
    {
        public const string HelseDirData =
                @"{""body"":{""current_page"":1,""data"":[{""id"":8,""name"":""LUNSJMENY UKE  5"",""description"":""Mandag\nSuppe: Tomatsuppe\nVarmrett: Bangers n' mash med l\u00f8ksjy og gr\u00f8nne erter\n\nTirsdag\nSuppe: Black bean soup\nVarmrett: Marinert laks med brokkoli, limer\u00f8mme og ris\n\nOnsdag\nSuppe: Kyllingsuppe\nVarmrett: Quiche med sopp, spinat, og mangosalsa\n \nTorsdag\nSuppe: Brokkolisuppe\nVarmrett: Fishtaco med fennikelslaw, og dill- og agurksalsa\n\nFredag\nSuppe: S\u00f8tpotet- og r\u00f8dcurrysuppe\nVarmrett: Fried chicken med Mac n' cheese og syrlig estragon-coleslaw\nDessert: Krydderkake med ost- og vaniljekrem"",""max"":null,""status"":0,""price"":null,""updated_by"":672,""created_by"":75,""deleted_by"":null,""created_at"":""2018-09-27 13:58:48"",""updated_at"":""2019-02-01 13:20:31"",""deleted_at"":null,""extra"":{""ingredients"":""Se allergenmerking ved maten""},""type"":null,""resource_type"":""canteens"",""resource_id"":2,""building_id"":2,""user_specific_price"":null,""user_specific_vat"":null,""canteen_id"":2,""categories"":[],""food_allergen_labels"":[],""vats"":[],""images"":[{""id"":9082,""name"":""KhDJV1538056810.png"",""type"":null,""title_key"":null,""url"":""https:\/\/workplace.izy.as\/storage\/images\/KhDJV1538056810.png"",""path"":""images\/KhDJV1538056810.png"",""image_url"":""https:\/\/workplace.izy.as\/storage\/images\/KhDJV1538056810.png""}]}],""first_page_url"":""https:\/\/workplace.izy.as\/api\/menuService-items\/featured?page=1"",""from"":1,""last_page"":1,""last_page_url"":""https:\/\/workplace.izy.as\/api\/menuService-items\/featured?page=1"",""next_page_url"":null,""path"":""https:\/\/workplace.izy.as\/api\/menuService-items\/featured"",""per_page"":15,""prev_page_url"":null,""to"":1,""total"":1},""status"":{""message"":""Okay"",""code"":""ok"",""code_text"":""ok"",""response_timestamp"":""2019-02-03T16:06:11+00:00""}}"
;
    }
}
