trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

- stage: Run
  jobs:
  - job: Delete
    displayName: Stop and delete old container
    pool: $(AgentPool)

    steps:
    - bash: 'docker rm -f $(ContainerName)'
      displayName: 'Bash Script'
      continueOnError: true

  - job: 
    displayName: Run new container from registry
    pool: $(AgentPool)

    steps:
    - bash: 'docker run --restart unless-stopped --name $(ContainerName) -d  -p 5000:80 -e ''BingSearchSubscriptionKey=$(BingSearchSubscriptionKey)'' -e ''OpenAiSubscriptionKey=$(OpenAiSubscriptionKey)'' -e ''IzyAsUsername=$(IzyAsUsername)'' -e ''IzyAsPassword=$(IzyAsPassword)'' $(registry)/$(imageRepository)/$(ContainerName):$(Build.BuildId)'
      displayName: 'Bash Script copy'