trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

- stage: Run
  displayName: Run new container
  jobs:
  - job: Run
    displayName: Run
    pool:
      name: $(AgentPool)
    steps:
      - task: Docker@2
        displayName: Login to Docker registry
        inputs:
          command: 'login'
          containerRegistry: $(dockerRegistryServiceConnection)

      - bash: 'docker rm -f $(ContainerName)'
        displayName: 'Remove old container'

      - bash: 'docker run --restart unless-stopped --name $(ContainerName) -d  -p 5000:80 -e "BingSearchSubscriptionKey=$(BingSearchSubscriptionKey)" -e "OpenAiSubscriptionKey=$(OpenAiSubscriptionKey)" -e "IzyAsUsername=$(IzyAsUsername)" -e "IzyAsPassword=$(IzyAsPassword)" $(registry)/$(imageRepository):$(Build.BuildId)'
        displayName: 'Start new container'